apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
  labels:
    app: be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: bepy
        image: nkangdra/be:1.0
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: be
spec:
  type: LoadBalancer
  selector:
    app: be
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      